### ISSUE TITLE
Frontend > Criar Estrutura de classes do projeto

### ISSUE THREAD

**Issue by lesorty** [Engenharia-de-software-Gp05/Fronted-Complexo-Esportivo-UFCG#4]
Nessa tarefa, você deve criar uma documentação de padronização do projeto. Para isso, é interessante que você estude a stack de forma profunda e entenda bons padrões usados no mercado. Os padrões devem incluir padrões de escrita de código, padrões de nomes de arquivos, padrões de pastas que serão usadas e seus nomes dentre outros que você julgar necessário.

**Atenção:** Note que essa é uma parte muito importante do projeto e que precisa de uma agilidade maior que as outras atividades.

Se tiver dúvidas, sinta-se a vontade para contatar o grupo de Frontend.

_Bom trabalho!_

**Comment by matheusvictoor** [comment]
Clique [aqui](https://matheusvictoor.notion.site/Documenta-o-do-Frotend-Projeto-Novo-1299f1bd45a34ac98ba7301b7c0b1c22) para ver a documentação de padronização do projeto.
